algoritmo "SomarDoisValores"
// Função :
// Autor :
// Data : 15/05/2019
// Seção de Declarações 
var
   v1, v2, S: Inteiro
   
Funcao Soma(X, Y: Inteiro): Inteiro
Inicio
      Retorne X + Y
FimFuncao
inicio
      Escreva("Digite o primeiro valor: ")
      Leia(v1)
      Escreva("Digite o segundo valor: ")
      Leia(v2)
      S <- Soma(v1, v2)
      Escreval("A soma entre ", v1, " e ", v2, " é igual a: ", s)
      

fimalgoritmo
