algoritmo "semnome"
// Função :
// Autor :
// Data : 01/02/2019
// Seção de Declarações 
var
   valor, salto, contador: inteiro
inicio
      contador <- 0
      Escreva("Informe um número: ")
      Leia(valor)
      Escreva("Qual sera o salto? ")
      Leia(salto)
      Enquanto (contador <= valor) faca
               Escreva(contador)
               contador <- contador + salto
      Fimenquanto
fimalgoritmo
